# Generated by Django 5.0.4 on 2024-04-26 10:57

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('lembrete_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'lembrete',
            },
        ),
    ]
