# Generated by Django 5.0.4 on 2024-04-25 23:43

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('lembrete_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='null', max_length=200)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.data')),
            ],
            options={
                'db_table': 'lembrete',
            },
        ),
    ]
