# Generated by Django 5.0.4 on 2024-04-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ('-data',)},
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
