# Generated by Django 5.0.4 on 2024-04-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
