# Generated by Django 5.0.4 on 2024-04-25 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lembrete_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='data',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
