# Generated by Django 5.0.4 on 2024-04-25 16:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_lembrete_data_alter_lembrete_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.data'),
        ),
    ]
