# Generated by Django 5.0.4 on 2024-04-28 08:39

import datetime
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_lembrete_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='data',
            field=models.DateField(default=datetime.date.today, validators=[main.models.validar_data_no_presente_ou_futuro]),
        ),
    ]
