# Generated by Django 5.0.4 on 2024-04-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_data_alter_lembrete_id_alter_lembrete_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='id',
            new_name='data_id',
        ),
        migrations.RenameField(
            model_name='lembrete',
            old_name='id',
            new_name='lembrete_id',
        ),
    ]
